In [1]:
import numpy as np
b = np.array([0,0,0,0,1,0,0,0])
def change_array(a):
    k=[]
    if a.ndim>1:
        for i in range(len(a)):
            for j in range(len(a[i])):
                k.append(a[i][j])
    else :
        for i in range(len(a)):
            k.append(a[i])
    return k

In [2]:
import numpy as np
a = np.array([[0,1,2],[3,4,5],[6,7,8]])
def sum(a):
    b=0
    for i in range (len(a)):
        b = b +a[i][i]
    return b
print(sum(a))

12


In [5]:
import numpy as np
b=int(input('donner x'))
x=int(input('donner le nombre de valeur que vous voulez inserer'))
y= int(input('si la dimention de votre array est 1 ecrivez 1 si elle est 2 ecrivez 2'))
m=[]
for i in range (x):
    m.append(int(input('donner les valeurs de votre liste une à une ')))
E=np.array(m)
if y == 2:
    z=int(input('donner le nombre de colonne que vous voulez '))
    j=int(input('donner le nombre de lignes que vous voulez'))
    E=E.reshape(j,z)
print(E)
def maxi(a ,x):
    m=[]
    if a.ndim>1:
        for i in range(len(a)):
            for j in range(len(a[i])):
                if a[i][j] > x :
                    m.append(a[i][j])
    else : 
        for i in range(len(a)):
            if a[i]> x :
                m.append(a[i])
    return m
print(maxi(E,b))

donner x4
donner le nombre de valeur que vous voulez inserer9
si la dimention de votre array est 1 ecrivez 1 si elle est 2 ecrivez 22
donner les valeurs de votre liste une à une 12
donner les valeurs de votre liste une à une 2
donner les valeurs de votre liste une à une 3
donner les valeurs de votre liste une à une 4
donner les valeurs de votre liste une à une 5
donner les valeurs de votre liste une à une 6
donner les valeurs de votre liste une à une 7
donner les valeurs de votre liste une à une 8
donner les valeurs de votre liste une à une 8
donner le nombre de colonne que vous voulez 3
donner le nombre de lignes que vous voulez3
[[12  2  3]
 [ 4  5  6]
 [ 7  8  8]]
[12, 5, 6, 7, 8, 8]


In [6]:
import numpy as np
def addition(A,B) :
    E=[]
    if A.ndim>1:
        row, col = A.shape
        for i in range(len(A)):
            for j in range(len(A[i])):
                E.append(A[i][j]+B[i][j])
        m=np.array(E)
        m = m.reshape(row,col)
    else:
        for i in range(len(A)):
            E.append(A[i]+B[i])
        m=np.array(E)
    return m
a = np.array([[0,1,2],[3,4,5],[6,7,8]])
b = np.array([[2,4,1],[6,4,2],[1,1,1]]) 
print(addition(a,b))  

[[2 5 3]
 [9 8 7]
 [7 8 9]]
